// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace ADefHelpDeskApp.Data.Models
{
    public partial class Categorys
    {
        public Categorys()
        {
            BlogCategory = new HashSet<BlogCategory>();
        }

        public int CategoryId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }

        public virtual ICollection<BlogCategory> BlogCategory { get; set; }
    }
}