// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdefHelpDeskBase.Models.DataContext
{
    public partial class AdefHelpDeskRoles
    {
        public AdefHelpDeskRoles()
        {
            AdefHelpDeskUserRoles = new HashSet<AdefHelpDeskUserRoles>();
        }

        public int Id { get; set; }
        public int PortalId { get; set; }
        public string RoleName { get; set; }

        public virtual ICollection<AdefHelpDeskUserRoles> AdefHelpDeskUserRoles { get; set; }
    }
}