// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdefHelpDeskBase.Models.DataContext
{
    public partial class AdefHelpDeskApiSecurityPermission
    {
        public int Id { get; set; }
        public int ApiSecurityUser { get; set; }
        public string PermissionName { get; set; }
        public bool IsEnabled { get; set; }

        public virtual AdefHelpDeskApiSecurity ApiSecurityUserNavigation { get; set; }
    }
}