// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdefHelpDeskBase.Models.DataContext
{
    public partial class AdefHelpDeskTaskAssociations
    {
        public int TaskRelationId { get; set; }
        public int TaskId { get; set; }
        public int AssociatedId { get; set; }

        public virtual AdefHelpDeskTasks Task { get; set; }
    }
}