// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdefHelpDeskBase.Models.DataContext
{
    public partial class AdefHelpDeskTaskDetails
    {
        public AdefHelpDeskTaskDetails()
        {
            AdefHelpDeskAttachments = new HashSet<AdefHelpDeskAttachments>();
        }

        public int DetailId { get; set; }
        public int TaskId { get; set; }
        public string DetailType { get; set; }
        public DateTime InsertDate { get; set; }
        public int UserId { get; set; }
        public string Description { get; set; }
        public DateTime? StartTime { get; set; }
        public DateTime? StopTime { get; set; }
        public string ContentType { get; set; }

        public virtual AdefHelpDeskTasks Task { get; set; }
        public virtual ICollection<AdefHelpDeskAttachments> AdefHelpDeskAttachments { get; set; }
    }
}